export const contractorActionTypes = {
    LOGIN_REQUEST: "CONTRACTOR_LOGIN_REQUEST",
    LOGIN_SUCCESS: "CONTRACTOR_LOGIN_SUCCESS",
    LOGIN_ERROR: "CONTRACTOR_LOGIN_ERROR",

    SIGNUP_REQUEST: "CONTRACTOR_SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "CONTRACTOR_SIGNUP_ERROR",
    SIGNUP_ERROR: "CONTRACTOR_SIGNUP_ERROR",

    LOGOUT: "CONTRACTOR_LOGOUT"
};