export const topOrganisationsActionTypes = {
    TOP_EMPLOYERS_REQUEST: "REQUEST_TOP_EMPLOYERS",
    TOP_EMPLOYERS_SUCCESS: "TOP_EMPLOYERS_SUCCESS",    
    TOP_EMPLOYERS_ERROR: "TOP_EMPLOYERS_ERROR",

    TOP_AGENCIES_REQUEST: "REQUEST_TOP_AGENCIES",
    TOP_AGENCIES_SUCCESS: "TOP_AGENCIES_SUCCESS",
    TOP_AGENCIES_ERROR: "TOP_AGENCIES_ERROR"
};